// <auto-generated />
using System;
using InClassAssignMent.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InClassAssignMent.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InClassAssignMent.Models.Customars.Customar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Muscabqaarey@gmail.com",
                            Name = "Muscab axmed",
                            Phone = "+252614463895"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mascudqaarey@gmail.com",
                            Name = "mascud axmed",
                            Phone = "+252614479457"
                        });
                });

            modelBuilder.Entity("InClassAssignMent.Models.ServiceType.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 50.00m,
                            Description = "Change engine oil and filter",
                            Name = "Oil Change"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 30.00m,
                            Description = "Rotate tires",
                            Name = "Tire Rotation"
                        });
                });

            modelBuilder.Entity("InClassAssignMent.Models.VehicleServiceType.VehicleServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ServiceDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceTypeId = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            ServiceDate = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceTypeId = 2,
                            VehicleId = 2
                        });
                });

            modelBuilder.Entity("InClassAssignMent.Models.Vehicles.Vehicles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomarId")
                        .HasColumnType("integer");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomarId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomarId = 1,
                            Make = "Marcedez",
                            Model = "Gwagon",
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            CustomarId = 2,
                            Make = "Honda",
                            Model = "Civic",
                            Year = 2021
                        });
                });

            modelBuilder.Entity("InClassAssignMent.Models.VehicleServiceType.VehicleServiceType", b =>
                {
                    b.HasOne("InClassAssignMent.Models.ServiceType.ServiceType", "ServiceType")
                        .WithMany("VehicleServiceTypes")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InClassAssignMent.Models.Vehicles.Vehicles", "Vehicle")
                        .WithMany("VehicleServiceTypes")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceType");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("InClassAssignMent.Models.Vehicles.Vehicles", b =>
                {
                    b.HasOne("InClassAssignMent.Models.Customars.Customar", "Customar")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customar");
                });

            modelBuilder.Entity("InClassAssignMent.Models.Customars.Customar", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("InClassAssignMent.Models.ServiceType.ServiceType", b =>
                {
                    b.Navigation("VehicleServiceTypes");
                });

            modelBuilder.Entity("InClassAssignMent.Models.Vehicles.Vehicles", b =>
                {
                    b.Navigation("VehicleServiceTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
